"""Opt-in cross-validation against the live QCDark2 reference implementation.

These tests import ``qcdark2.dark_matter_rates`` from the QCDark2 checkout that
DataRegistry resolves (DMERATES_QCDARK2_ROOT env var or the ../QCDark2 sibling)
and compare the DMeRates SRDM dielectric engine against the reference
``get_rate_flux()`` directly, rather than against pinned notebook numbers.
They are skipped automatically when the reference code or data is absent, so
the default test suite is unaffected on machines without the checkout.

Added after the 2026-06 physics review, which found two gaps in the stored
validation evidence:

1. The mediator-mode notebook (validation/qcdark2_srdm_mediator_modes.ipynb)
   has no stored outputs, and the scalar/approx/approx_full reference values in
   conftest.py were generated by the DMeRates reimplementation itself. Here all
   four modes are checked against the reference code. vector/scalar/approx are
   expected to differ from the reference ONLY through the documented propagator
   convention fix — DMeRates uses the paper's (omega^2 - q^2 - m_A^2)^2 where
   the reference code has (omega - q^2 - m_A^2)^2 — observed max 0.1% at this
   benchmark. approx_full has no omega in its propagator, so it matches to
   float precision (observed 1.3e-7).
2. The FDMn=0 (heavy mediator) SRDM path had no benchmark at all, because the
   flux manifest only carries FDMn=2 DPLM entries. Here the same flux table is
   injected into both codes and the heavy-mediator kernel (m_A proxy 1e10 eV)
   is compared directly (observed 1.3e-7).

NOTE on numericalunits: build nu-scaled quantities only inside fixtures/tests
(units are frozen once conftest imports DMeRates), never at module import time
in scripts that import DMeRates afterwards.
"""
import sys
sys.path.insert(0, ".")

import numpy as np
import pytest

from DMeRates.data.registry import DataRegistry
from DMeRates.engines.dielectric import _LARGE_MA_EV, compute_dRdE

_QCDARK2_ROOT = DataRegistry.qcdark2_root
_REFERENCE_CODE = _QCDARK2_ROOT / "qcdark2" / "dark_matter_rates.py"
_SI_COMP_PATH = DataRegistry.qcdark2_dielectric("Si", "composite")
_FLUX_PATH = DataRegistry.srdm_flux_file("srdm_dphidv_DPLM_row10_col8.txt")

QCDARK2_REFERENCE_AVAILABLE = (
    _REFERENCE_CODE.is_file() and _SI_COMP_PATH.is_file() and _FLUX_PATH.is_file()
)

pytestmark = pytest.mark.skipif(
    not QCDARK2_REFERENCE_AVAILABLE,
    reason=(
        "QCDark2 reference code/data not found. Need a QCDark2 checkout at "
        f"{_QCDARK2_ROOT} containing qcdark2/dark_matter_rates.py and "
        f"dielectric data, plus {_FLUX_PATH}."
    ),
)

# Registered Si SRDM benchmark (same point as tests/test_qcdark2_srdm.py).
_MX_EV = 48232.9466
_SIGMA_E_CM2 = 1.098541e-38

# vector/scalar/approx tolerance covers the propagator convention difference
# (observed max ~1e-3 at this benchmark); approx_full and the heavy-mediator
# kernel share the reference's propagator exactly (observed ~1.3e-7).
_PROPAGATOR_CONVENTION_TOL = 5e-3
_EXACT_KERNEL_TOL = 1e-5


@pytest.fixture(scope="module")
def reference():
    """Import the QCDark2 reference module and load the Si dielectric."""
    sys.path.insert(0, str(_QCDARK2_ROOT))
    try:
        from qcdark2 import dark_matter_rates as dmr
    finally:
        sys.path.remove(str(_QCDARK2_ROOT))
    eps = dmr.df(str(_SI_COMP_PATH))
    return dmr, eps


@pytest.fixture(scope="module")
def dplm_flux():
    """Benchmark DPLM flux as bare floats: v/c and dPhi/d(v/c) in cm^-2 s^-1."""
    data = np.loadtxt(str(_FLUX_PATH), comments="#")
    v_kms, dphi_kms = data[:, 0], data[:, 1]
    positive = v_kms > 0.0  # SRDM cross sections carry 1/v^2
    c_kms = 299792.458
    v_over_c = v_kms[positive] / c_kms
    dphi_dvoc = dphi_kms[positive] * c_kms
    return v_over_c, dphi_dvoc


def _max_rel_diff(mine, ref):
    """Max relative difference over energies above 5% of the reference peak."""
    sel = ref > 0.05 * ref.max()
    return float(np.max(np.abs(mine[sel] - ref[sel]) / ref[sel]))


@pytest.mark.parametrize(
    "ref_mode,my_mode,tol",
    [
        ("vector", "vector", _PROPAGATOR_CONVENTION_TOL),
        ("scalar", "scalar", _PROPAGATOR_CONVENTION_TOL),
        ("approx", "approx", _PROPAGATOR_CONVENTION_TOL),
        ("approx full", "approx_full", _EXACT_KERNEL_TOL),
    ],
)
def test_srdm_light_mediator_modes_match_reference(
    fix_units, reference, dplm_flux, ref_mode, my_mode, tol
):
    dmr, eps = reference
    v_over_c, dphi_dvoc = dplm_flux

    ref = dmr.get_rate_flux(
        eps, _MX_EV, _SIGMA_E_CM2, dphi_dvoc, v_over_c,
        m_A=0.0, mediator=ref_mode, screening="RPA",
    )
    mine = compute_dRdE(
        material="Si",
        mX_eV=_MX_EV,
        FDMn=2,
        halo_model="srdm",
        screening="rpa",
        sigma_e_cm2=_SIGMA_E_CM2,
        mediator_spin=my_mode,
    ).dRdE_per_kg_per_year_per_eV

    rel = _max_rel_diff(mine, ref)
    assert rel < tol, (
        f"mode={my_mode}: max rel diff {rel:.3e} vs QCDark2 reference "
        f"exceeds tolerance {tol:.0e}."
    )


def test_srdm_heavy_mediator_matches_reference(
    fix_units, reference, dplm_flux, monkeypatch
):
    """FDMn=0 kernel vs reference with the same m_A -> infinity proxy.

    The flux manifest only registers FDMn=2 entries, so the benchmark flux is
    injected into the engine through the loader boundary. This reuses an
    FDMn=2-generated flux table purely as a numerical input; the comparison
    exercises the heavy-mediator detector kernel, not flux provenance.
    """
    import numericalunits as nu
    import torch

    import DMeRates.srdm.flux_loader as flux_loader

    dmr, eps = reference
    v_over_c, dphi_dvoc = dplm_flux

    ref = dmr.get_rate_flux(
        eps, _MX_EV, _SIGMA_E_CM2, dphi_dvoc, v_over_c,
        m_A=_LARGE_MA_EV, mediator="vector", screening="RPA",
    )

    v_tensor = torch.tensor(v_over_c, dtype=torch.float64)
    dphi_tensor = torch.tensor(dphi_dvoc, dtype=torch.float64) / float(
        nu.cm**2 * nu.s
    )

    def fake_resolve(**kwargs):
        return v_tensor, dphi_tensor, {
            "flux_file": "injected-benchmark-flux",
            "flux_source": "test",
        }

    monkeypatch.setattr(flux_loader, "resolve_srdm_flux_source", fake_resolve)

    mine = compute_dRdE(
        material="Si",
        mX_eV=_MX_EV,
        FDMn=0,
        halo_model="srdm",
        screening="rpa",
        sigma_e_cm2=_SIGMA_E_CM2,
        mediator_spin="vector",
    ).dRdE_per_kg_per_year_per_eV

    rel = _max_rel_diff(mine, ref)
    assert rel < _EXACT_KERNEL_TOL, (
        f"FDMn=0 heavy mediator: max rel diff {rel:.3e} vs QCDark2 reference "
        f"exceeds tolerance {_EXACT_KERNEL_TOL:.0e}."
    )
